### ISSUE TITLE
Crystal version

### ISSUE THREAD

**Issue by krthr** [lukeed/uuid#1]
I have written the Crystal version of this lib: https://github.com/krthr/uuix

**Comment by lukeed** [comment]
Cool!! I was likely gunna do one in Rust, but dunno how well others already perform.

**Comment by krthr** [comment]
The benchmark for Crystal is pretty amazing:

```
Crystal 0.33.0 [612825a53] (2020-02-14)

LLVM: 8.0.0
Default target: x86_64-unknown-linux-gnu
        UUIX: 920.14k (  1.09µs) (± 9.68%)  880B/op        fastest
Crystal UUID: 647.32k (  1.54µs) (± 7.53%)  0.0B/op   1.42× slower
```

Awesome!

**Comment by lukeed** [comment]
I saw that – very exciting :D

**Comment by krthr** [comment]
Thanks to @skuznetsov, some optimizations have been made. We have achieved quite good results.

```bash
bash-3.2$ ./benchmark
Crystal 0.33.0 (2020-02-14)

LLVM: 9.0.1
Default target: x86_64-apple-macosx
        UUIX:   4.67M (213.98ns) (± 3.00%)  113B/op        fastest
Crystal UUID: 783.57k (  1.28µs) (± 2.15%)  0.0B/op   5.96× slower
```

It would be great to see implementations in other languages.

**Comment by lukeed** [comment]
haha wow! That's a major jump!

I just pushed some changes to this repo and it increased JS performance by ~200k op/s on my machine. I have a new "math" mode incoming that is _not_ crypto-safe but is 1M op/s faster.

**Comment by skuznetsov** [comment]
I was able to achieve even more impressive speed on my MacBook:
```bash-3.2$ ./benchmark
Crystal 0.33.0 (2020-02-14)

LLVM: 9.0.1
Default target: x86_64-apple-macosx
        UUIX:   5.92M (169.04ns) (±10.99%)  113B/op        fastest
Crystal UUID: 770.02k (  1.30µs) (± 3.55%)  0.0B/op   7.68× slower
```
This is with secure random buffer equal to 16MB and 1 byte shift (instead of original 16 as it is still unique and probability of generation of the same sequence is even less possible than with shift to 16) so it is quite good results with just 169 nanoseconds per one hash (including random data generation).
Also by some reason 16 MB buffer is fastest. sizes above and below are giving lower results.

**Comment by lukeed** [comment]
That's awesome! Let me see if I understand correctly:

You've modified this so that your window is inching along the pre-allocated Buffer 1 byte as a time (as opposed to a full chunk) 😂 That's so simple – great tweak!

```js
var BUFFER = '123456...';

uuid(); // => '123...';
uuid(); // => '234...';
uuid(); // => '345...';
```

**Comment by lukeed** [comment]
Here are new numbers with that approach :)

```
  @lukeed/next                 x 6,447,983 ops/sec ±0.31% (93 runs sampled)
  @lukeed/uuid                 x 2,544,311 ops/sec ±0.30% (94 runs sampled)
```

**Comment by lukeed** [comment]
Hope you don't mind that I've closed this @krthr – only because it's not an "issue" 

I really appreciate you porting this & sharing it! This is a first for me 🎉
