### ISSUE TITLE
React Native version

### ISSUE THREAD

**Issue by aleclarson** [lukeed/uuid#4]
React Native's bundler currently uses the browser version of this library, which is incompatible due to usage of the `crypto` global namespace. I *could* polyfill the `crypto` global using [`react-native-crypto`](https://www.npmjs.com/package/react-native-crypto), but that would [bloat](https://bundlephobia.com/result?p=react-native-crypto) my bundle (which goes against the ethos of this library of yours).

So my question is, would you mind adding a React Native version of this module that uses pure JavaScript, no native code? That would let me use this library in an isomorphic package of mine that I intend to use in both React Native and browsers.

While it seems that bundle size and speed are the main goals of this library, I'd be fine with giving up some speed just to keep native code out of this package.

**Comment by lukeed** [comment]
Hey,

A main goal here, more than size, is that it's cryptographically secure. I don't particularly want (or think I should) include non-CSPRNG variants alongside the primary CSPRING goal. It would be confusing and would also require you to import/require a different entry path, which isn't much different than using a separate module or aliasing a module thru your bundler.

If you don't care about the randomness of the generation, you might want to use `uuid/v4` directly or the standalone JS implementation I [included in the benchmark](https://github.com/lukeed/uuid/blob/master/bench/index.js#L7-L13), which is still faster than `uuid/v4`

Let me know if that helps~!

**Comment by aleclarson** [comment]
That's a fair point. I'll use `@lukeed/uid` instead since I don't need the CS part for my use case. Thanks!

PS: By default, the React Native bundler prefers modules ending in `.native.js`, so you could generate a `dist/index.native.js` bundle for RN users to consume, sans any effort on their end. But I digress. :)

**Comment by lukeed** [comment]
Thanks :) TIL
