### ISSUE TITLE
How does this library compare to Node.js built-in crypto.randomUUID ?

### ISSUE THREAD

**Issue by GrosSacASac** [lukeed/uuid#6]
https://nodejs.org/api/crypto.html#crypto_crypto_randomuuid_options

Is it the same ?

**Comment by lukeed** [comment]
Same idea; this library came first and does not have a "no cache" option. I'm not aware of the performance differences but I imagine it's the same since native is using more or less the same approach I've used here.

**Comment by lukeed** [comment]
Of course, I'm comparing `crypto.randomUUID` with `@lukeed/uuid/secure`, since they're both CSPRNG-based. 

The default `@lukeed/uuid` uses Math.random, which is much faster. The README gets into the differences
