### ISSUE TITLE
Presents a magical repetition

### ISSUE THREAD

**Issue by MineYuanlu** [lukeed/uuid#8]
I'm generating a series of UUIDs in succession, and they show a strange repetition, moving forward 2 bits at a time, but the rest remains the same
![图片](https://user-images.githubusercontent.com/38997444/169111072-c9b9928e-3622-467a-94ae-89e093307331.png)

**Comment by lukeed** [comment]
Intentional. All are still valid & unique UUIDv4s, reusing the internal buffer
