### ISSUE TITLE
Secure uuid breaks on Node v17.9.0

### ISSUE THREAD

**Issue by tonystr** [lukeed/uuid#9]
OS: Windows 11
Browser: Firefox 112.0b8 (64-bit)
Node: v17.9.0
```
Uncaught TypeError: import_crypto.randomBytes is not a function
    random @lukeed_uuid_secure.js:22
    v4 @lukeed_uuid_secure.js:35
    sendMessage ChatPanel.vue:120
...
```
The secure uuidv4 function breaks on node v17.9.0

**Comment by evenstensberg** [comment]
@lukeed Might this be a compiler issue, where polyfills for cyrpto aren't included?

**Comment by lukeed** [comment]
1. Don’t use odd numbered Node versions. These are always experimental versions and are never meant to be used long term. 

2. This is a bundler config issue. The crypto native Node module is available in all Node versions. Something you’re using is trying to import or rely on a 3rd party “crypto” package which must not offer the export. Whatever set up you have is missing a ~”prefer builtins” plugin or configuration toggle
